version: '3'
services:
    php:
        build:
            context: ./php
        restart: always
        volumes:
            - ./app:/var/www/html/app
        container_name: "App"
    nginx:
        image: nginx:latest
        restart: always
        ports:
            - "4888:80"
        volumes:
            - ./app:/var/www/html/app
            - ./nginx/app.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php
    mysql:
        image: mysql:8
        restart: always
        ports:
            - "4333:3306"
        environment:
            MYSQL_ROOT_PASSWORD: toor
        volumes:
            - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
        container_name: "AppMysql"
    adminer:
        image: adminer
        restart: always
        ports:
            - "4081:8080"
