nelmio_api_doc:
    documentation:
        info:
            title: Quests
            description: User Task Management Service 
            version: 1.0.0
    areas:
        path_patterns:
            - ^/api(?!/doc$)
